# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

# Require `revel` command (compiled later from vendor dir)
required = ["github.com/revel/cmd/revel"]
[[constraint]]
  name = "github.com/revel/cmd"
  version = "v0.14.1"

# Override version for transitive dependencies
# otherwise we fetch the latest.
[[override]]
  name = "github.com/revel/config"
  version = "v0.14.0"
[[override]]
  name = "github.com/revel/modules"
  version = "v0.14.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "v0.14.0"

[[constraint]]
  name = "github.com/youtube/vitess"
  branch = "master"
